CREATE TABLE IF NOT EXISTS analysis_results (
    id SERIAL PRIMARY KEY,
    text TEXT NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    action VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);